### ISSUE TITLE
Oracle Price

### ISSUE THREAD

**Issue by maco2035** [rsnodgrass/hass-helium#3]
Hello!

I added this to the configurarion.yaml
```
sensor:
  - platform: helium
    hotspots:
        - xxx
        - yyy
        - zzz
        - aaa
        - bbb
```

So when I attempt to use the `sensor.helium_hnt_oracle_price` I get the following error `Entity not available: sensor.helium_hnt_oracle_price`

I don't know what I am doing wrong. I think it might be a config mistake, or something else.
