### ISSUE TITLE
Wallet Value example

### ISSUE THREAD

**Issue by thomasgregg** [rsnodgrass/hass-helium#9]
Hi,

In your documentation you list the below example. I modified it in the way that it fits my wallet sensor and put it unser sensor: (I hope that's right).

```
sensor:
  - platform: template
    sensors:
      helium_wallet_value:
        value_template:
          "{{ sensor.helium_hnt_oracle_price * sensor.helium_wallet_xyz123 }}"  
```

If i restart HA the helium_wallet_value will not be loaded correctly.

![image](https://user-images.githubusercontent.com/2538782/144760160-66dd147d-d020-4fb3-9897-d80a2c20dc6b.png)

The log says:

`2021-12-05 19:52:23 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'sensor' is undefined when rendering '{{ sensor.helium_hnt_oracle_price * sensor.helium_wallet_14db9nt729l2uocitdbpdjzr6kq1l1ceiuesutfivrvpqn7bvdz }}'
2021-12-05 19:52:23 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ sensor.helium_hnt_oracle_price * sensor.helium_wallet_14db9nt729l2uocitdbpdjzr6kq1l1ceiuesutfivrvpqn7bvdz }}")`

Not really sure if this is related to my poor HA skills or to the integration. But would be great if you would have an idea or could help. 

Thanks.
